name: IT

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  nightly:
    if: github.repository == 'primefaces/primefaces' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}, ${{ matrix.profile }}
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17]
        profile: [ 'firefox,theme-saga,myfaces-2.3', 'firefox,csp,theme-saga,myfaces-2.3', 'chrome,theme-saga,myfaces-2.3', 'chrome,theme-saga,myfaces-next-2.3','chrome,csp,theme-nova,myfaces-2.3', 'chrome,csp,theme-nova,mojarra-2.3', 'chrome,client-state-saving,theme-nova,mojarra-2.3' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Log github.ref
        run: echo "${{ github.ref }}"
      - name: Build
        run: mvn clean install -Dmaven.javadoc.skip=true -Djsdoc.skip.typedoc=true --batch-mode --show-version
      - name: Integration Tests
        run: mvn -B -V clean install -fprimefaces-integration-tests/pom.xml -Pintegration-tests,headless,${{ matrix.profile }}
