name: Nightly Build (FileUpload)

on:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: read

jobs:
  nightly:
    if: github.repository == 'primefaces/primefaces' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}, Profile ${{ matrix.profile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11
            profile: 'headless,firefox,myfaces-4.0'
          - java: 11
            profile: 'headless,firefox,mojarra-4.0'
          - java: 11
            profile: 'headless,chrome,myfaces-4.0'
          - java: 11
            profile: 'headless,chrome,mojarra-4.0'
          - java: 17
            profile: 'headless,firefox,myfaces-4.1'
          - java: 17
            profile: 'headless,firefox,mojarra-4.1'
          - java: 17
            profile: 'headless,chrome,myfaces-4.1'
          - java: 17
            profile: 'headless,chrome,mojarra-4.1'

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Log github.ref
        run: echo "${{ github.ref }}"
      - name: Build
        run: mvn clean install -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 --batch-mode --show-version
      - name: Integration Tests FileUpload
        run: >
            mvn -B -V clean install -fprimefaces-integration-tests/pom.xml -Pintegration-tests,${{ matrix.profile }}
            -Dit.test=org.primefaces.integrationtests.fileupload.FileUpload*Test
