name: IT FileUpload

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  nightly:
    if: github.repository == 'primefaces/primefaces' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}, Profile ${{ matrix.profile }}
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
        profile: [
          'headless,firefox,myfaces-2.3,uploader-native', 'headless,firefox,mojarra-2.3,uploader-native',
          'headless,firefox,myfaces-2.3,uploader-commons', 'headless,firefox,mojarra-2.3,uploader-commons',
          'headless,chrome,myfaces-2.3,uploader-native', 'headless,chrome,mojarra-2.3,uploader-native',
          'headless,chrome,myfaces-2.3,uploader-commons', 'headless,chrome,mojarra-2.3,uploader-commons'
        ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Log github.ref
        run: echo "${{ github.ref }}"
      - name: Build
        run: mvn clean install --batch-mode --show-version
      - name: Integration Tests FileUpload
        run: >
            mvn -B -V clean install -fprimefaces-integration-tests/pom.xml -Pintegration-tests,${{ matrix.profile }}
            -Dit.test=org.primefaces.integrationtests.fileupload.FileUpload*Test
